using Microsoft.Maui.Controls.Xaml;

namespace NutritionTracker.Services;

public static class LocalizationService
{
    private static readonly Dictionary<string, string> Fr = new()
    {
        ["tab_dashboard"] = "Tableau",
        ["tab_diary"] = "Journal",
        ["tab_add"] = "Ajouter",
        ["tab_goals"] = "Objectifs",
        ["tab_profile"] = "Profil",

        ["dashboard_title"] = "Tableau",
        ["hello"] = "Bonjour,",
        ["record_meal_plus"] = "Enregistrer un repas +",
        ["advice"] = "Conseils",
        ["goals"] = "Objectifs",
        ["daily_summary"] = "Résumé du jour",
        ["daily_summary_hint"] = "Ajoutez vos repas (texte ou photo) pour suivre calories, protéines et glucides.",
        ["steps"] = "Pas",
        ["burned_calories"] = "Calories dépensées",
        ["net_calories"] = "Net calorique: {0}",
        ["reward_streak_title"] = "Série d'équilibre",
        ["reward_streak_subtitle"] = "Gagnez une flamme chaque jour équilibré (objectifs + charge).",
        ["reward_balanced_today"] = "Objectifs équilibrés aujourd'hui : +1 flamme",
        ["reward_not_balanced_today"] = "Continuez : approchez calories nettes, protéines et glucides",
        ["reward_status_good"] = "Statut du jour : Équilibré ✅",
        ["reward_status_pending"] = "Statut du jour : À valider",
        ["recording_streak_title"] = "Série d'enregistrement",
        ["coins_balance"] = "Solde de pièces",
            ["reminder_title"] = "Rappels repas",
            ["reminder_enabled"] = "Activer",
            ["reminder_breakfast"] = "Petit-déjeuner (HH:mm)",
            ["reminder_lunch"] = "Déjeuner (HH:mm)",
            ["reminder_dinner"] = "Dîner (HH:mm)",
            ["save_reminders"] = "Enregistrer les rappels",
            ["reminders_saved"] = "Rappels mis à jour",
    ["backend_api_placeholder"] = "https://api.nutritiontracker.fr",
            ["invite_email_placeholder"] = "email@exemple.com",
            ["invite_friend"] = "Inviter",
            ["accept"] = "Accepter",
            ["remove"] = "Supprimer",
            ["invite_invalid_email"] = "Email invalide",
            ["invite_already_exists"] = "Déjà invité ou déjà ami",
            ["invite_sent"] = "Invitation envoyée",
            ["friend_accepted"] = "Ami ajouté",
            ["friend_removed"] = "Entrée supprimée",
            ["status_pending"] = "Invitation en attente",
            ["status_friend"] = "Ami",
            ["backend_api_title"] = "API Backend (PostgreSQL)",
            ["backend_api_placeholder"] = "https://api.nutritiontracker.fr",
            ["save_backend_api"] = "Enregistrer API",
            ["backend_api_saved_ok"] = "API enregistrée et identité synchronisée",
            ["backend_api_saved_local_only"] = "API enregistrée (mode local seulement)",
            ["saved_title_common"] = "Enregistré",
            ["goals_saved_message"] = "Objectifs mis à jour.\n+5 pièces gagnées · Solde : {0}",

        ["login_title"] = "Connexion",
        ["login_subtitle"] = "Suivez calories, protéines et glucides à partir d'un texte ou d'une photo.",
        ["login_google"] = "Continuer avec Google",
        ["login_disclaimer"] = "En continuant, vous acceptez d'envoyer vos données de repas au service d'analyse.",

        ["goals_title"] = "Objectifs",
        ["goal_cal_day"] = "Objectif calories / jour",
        ["goal_protein_day"] = "Objectif protéines / jour",
        ["goal_carbs_day"] = "Objectif glucides / jour",
        ["save"] = "Enregistrer",

        ["profile_title"] = "Profil",
        ["language"] = "Langue",
        ["current_lang_fr"] = "Langue actuelle : Français",
        ["current_lang_en"] = "Langue actuelle : Anglais",
        ["steps_today"] = "Pas aujourd'hui",
        ["advice_title"] = "Conseils",
        ["advice_hint"] = "Générez des recommandations basées sur votre historique.",
        ["generate_reco"] = "Générer des recommandations",
        ["logout"] = "Se déconnecter",

        ["main_loading"] = "Chargement...",

        ["recommendations_title"] = "Conseils",
        ["actions"] = "Actions :",

        ["sync_ok"] = "Google Fit synchronisé",
        ["sync_no_token"] = "Reconnectez-vous pour autoriser Google Fit",
        ["sync_error"] = "Sync Google Fit en échec",
        ["sync_disabled"] = "Intégration Google Fit temporairement désactivée",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["tab_dashboard"] = "Dashboard",
        ["tab_diary"] = "Diary",
        ["tab_add"] = "Add",
        ["tab_goals"] = "Goals",
        ["tab_profile"] = "Profile",

        ["dashboard_title"] = "Dashboard",
        ["hello"] = "Hello,",
        ["record_meal_plus"] = "Log meal +",
        ["advice"] = "Advice",
        ["goals"] = "Goals",
        ["daily_summary"] = "Daily summary",
        ["daily_summary_hint"] = "Add meals (text or photo) to track calories, protein and carbs.",
        ["steps"] = "Steps",
        ["burned_calories"] = "Burned calories",
        ["net_calories"] = "Net calories: {0}",
        ["reward_streak_title"] = "Balance streak",
        ["reward_streak_subtitle"] = "Earn one flame for each balanced day (goals + load).",
        ["reward_balanced_today"] = "Balanced today: +1 flame",
        ["reward_not_balanced_today"] = "Keep going: align net calories, protein and carbs",
        ["reward_status_good"] = "Today status: Balanced ✅",
        ["reward_status_pending"] = "Today status: Pending",
            ["recording_streak_title"] = "Logging streak",
            ["coins_balance"] = "Coins balance",
            ["reminder_title"] = "Meal reminders",
            ["reminder_enabled"] = "Enable",
            ["reminder_breakfast"] = "Breakfast (HH:mm)",
            ["reminder_lunch"] = "Lunch (HH:mm)",
            ["reminder_dinner"] = "Dinner (HH:mm)",
            ["save_reminders"] = "Save reminders",
            ["reminders_saved"] = "Reminders updated",
    ["backend_api_placeholder"] = "https://api.nutritiontracker.fr",
            ["invite_email_placeholder"] = "email@example.com",
            ["invite_friend"] = "Invite",
            ["accept"] = "Accept",
            ["remove"] = "Remove",
            ["invite_invalid_email"] = "Invalid email",
            ["invite_already_exists"] = "Already invited or already friend",
            ["invite_sent"] = "Invite sent",
            ["friend_accepted"] = "Friend added",
            ["friend_removed"] = "Entry removed",
            ["status_pending"] = "Pending invite",
            ["status_friend"] = "Friend",
            ["backend_api_title"] = "Backend API (PostgreSQL)",
            ["backend_api_placeholder"] = "https://api.nutritiontracker.fr",
            ["save_backend_api"] = "Save API",
            ["backend_api_saved_ok"] = "API saved and identity synced",
            ["backend_api_saved_local_only"] = "API saved (local-only mode)",
            ["saved_title_common"] = "Saved",
            ["goals_saved_message"] = "Goals updated.\n+5 coins earned · Balance: {0}",

        ["login_title"] = "Login",
        ["login_subtitle"] = "Track calories, protein and carbs from text or photo.",
        ["login_google"] = "Continue with Google",
        ["login_disclaimer"] = "By continuing, you agree to send meal data to the analysis service.",

        ["goals_title"] = "Goals",
        ["goal_cal_day"] = "Calories target / day",
        ["goal_protein_day"] = "Protein target / day",
        ["goal_carbs_day"] = "Carbs target / day",
        ["save"] = "Save",

        ["profile_title"] = "Profile",
        ["language"] = "Language",
        ["current_lang_fr"] = "Current language: French",
        ["current_lang_en"] = "Current language: English",
        ["current_lang_pt"] = "Current language: Portuguese (Brazil)",
        ["current_lang_es"] = "Current language: Spanish (LatAm)",
        ["steps_today"] = "Today's steps",
        ["advice_title"] = "Advice",
        ["advice_hint"] = "Generate recommendations from your history.",
        ["generate_reco"] = "Generate recommendations",
        ["logout"] = "Sign out",

        ["main_loading"] = "Loading...",

        ["recommendations_title"] = "Advice",
        ["actions"] = "Actions:",

        ["sync_ok"] = "Google Fit synced",
        ["sync_no_token"] = "Sign in again to allow Google Fit",
        ["sync_error"] = "Google Fit sync failed",
        ["sync_disabled"] = "Google Fit integration temporarily disabled",
    };

    private static readonly Dictionary<string, string> Pt = new()
    {
        ["tab_dashboard"] = "Painel",
        ["tab_diary"] = "Diário",
        ["tab_add"] = "Adicionar",
        ["tab_goals"] = "Metas",
        ["tab_profile"] = "Perfil",
        ["dashboard_title"] = "Painel",
        ["hello"] = "Olá,",
        ["record_meal_plus"] = "Registrar refeição +",
        ["advice"] = "Conselhos",
        ["goals"] = "Metas",
        ["daily_summary"] = "Resumo diário",
        ["daily_summary_hint"] = "Adicione refeições (texto ou foto) para acompanhar calorias, proteínas e carboidratos.",
        ["steps"] = "Passos",
        ["burned_calories"] = "Calorias queimadas",
        ["net_calories"] = "Calorias líquidas: {0}",
        ["reward_streak_title"] = "Sequência de equilíbrio",
        ["reward_streak_subtitle"] = "Ganhe uma chama para cada dia equilibrado (metas + carga).",
        ["reward_balanced_today"] = "Equilibrado hoje: +1 chama",
        ["reward_not_balanced_today"] = "Continue: alinhe calorias líquidas, proteínas e carboidratos",
        ["reward_status_good"] = "Status de hoje: Equilibrado ✅",
        ["reward_status_pending"] = "Status de hoje: Pendente",
        ["recording_streak_title"] = "Sequência de registros",
        ["coins_balance"] = "Saldo de moedas",
        ["reminder_title"] = "Lembretes de refeição",
        ["reminder_enabled"] = "Ativar",
        ["reminder_breakfast"] = "Café da manhã (HH:mm)",
        ["reminder_lunch"] = "Almoço (HH:mm)",
        ["reminder_dinner"] = "Jantar (HH:mm)",
        ["save_reminders"] = "Salvar lembretes",
        ["reminders_saved"] = "Lembretes atualizados",
        ["friends_title"] = "Amigos e convites",
        ["invite_email_placeholder"] = "email@exemplo.com",
        ["invite_friend"] = "Convidar",
        ["accept"] = "Aceitar",
        ["remove"] = "Remover",
        ["invite_invalid_email"] = "Email inválido",
        ["invite_already_exists"] = "Já convidado ou já amigo",
        ["invite_sent"] = "Convite enviado",
        ["friend_accepted"] = "Amigo adicionado",
        ["friend_removed"] = "Entrada removida",
        ["status_pending"] = "Convite pendente",
        ["status_friend"] = "Amigo",
        ["backend_api_title"] = "API Backend (PostgreSQL)",
        ["backend_api_placeholder"] = "https://api.nutritiontracker.fr",
        ["save_backend_api"] = "Salvar API",
        ["backend_api_saved_ok"] = "API salva e identidade sincronizada",
        ["backend_api_saved_local_only"] = "API salva (modo local)",
        ["saved_title_common"] = "Salvo",
        ["goals_saved_message"] = "Metas atualizadas.\n+5 moedas ganhas · Saldo: {0}",
        ["login_title"] = "Entrar",
        ["login_subtitle"] = "Acompanhe calorias, proteínas e carboidratos por texto ou foto.",
        ["login_google"] = "Continuar com Google",
        ["login_disclaimer"] = "Ao continuar, você concorda em enviar dados ao serviço de análise.",
        ["goals_title"] = "Metas",
        ["goal_cal_day"] = "Meta de calorias / dia",
        ["goal_protein_day"] = "Meta de proteínas / dia",
        ["goal_carbs_day"] = "Meta de carboidratos / dia",
        ["save"] = "Salvar",
        ["profile_title"] = "Perfil",
        ["language"] = "Idioma",
        ["current_lang_fr"] = "Idioma atual: Francês",
        ["current_lang_en"] = "Idioma atual: Inglês",
        ["current_lang_pt"] = "Idioma atual: Português (Brasil)",
        ["current_lang_es"] = "Idioma atual: Espanhol (LatAm)",
        ["steps_today"] = "Passos de hoje",
        ["advice_title"] = "Conselhos",
        ["advice_hint"] = "Gere recomendações com base no seu histórico.",
        ["generate_reco"] = "Gerar recomendações",
        ["logout"] = "Sair",
        ["main_loading"] = "Carregando...",
        ["recommendations_title"] = "Conselhos",
        ["actions"] = "Ações:",
        ["sync_ok"] = "Google Fit sincronizado",
        ["sync_no_token"] = "Entre novamente para autorizar Google Fit",
        ["sync_error"] = "Falha na sincronização do Google Fit",
        ["sync_disabled"] = "Integração com Google Fit temporariamente desativada",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["tab_dashboard"] = "Panel",
        ["tab_diary"] = "Diario",
        ["tab_add"] = "Añadir",
        ["tab_goals"] = "Objetivos",
        ["tab_profile"] = "Perfil",
        ["dashboard_title"] = "Panel",
        ["hello"] = "Hola,",
        ["record_meal_plus"] = "Registrar comida +",
        ["advice"] = "Consejos",
        ["goals"] = "Objetivos",
        ["daily_summary"] = "Resumen diario",
        ["daily_summary_hint"] = "Añade comidas (texto o foto) para seguir calorías, proteínas y carbohidratos.",
        ["steps"] = "Pasos",
        ["burned_calories"] = "Calorías quemadas",
        ["net_calories"] = "Calorías netas: {0}",
        ["reward_streak_title"] = "Racha de equilibrio",
        ["reward_streak_subtitle"] = "Gana una llama por cada día equilibrado (objetivos + carga).",
        ["reward_balanced_today"] = "Equilibrado hoy: +1 llama",
        ["reward_not_balanced_today"] = "Sigue: ajusta calorías netas, proteínas y carbohidratos",
        ["reward_status_good"] = "Estado de hoy: Equilibrado ✅",
        ["reward_status_pending"] = "Estado de hoy: Pendiente",
        ["recording_streak_title"] = "Racha de registro",
        ["coins_balance"] = "Saldo de monedas",
        ["reminder_title"] = "Recordatorios de comida",
        ["reminder_enabled"] = "Activar",
        ["reminder_breakfast"] = "Desayuno (HH:mm)",
        ["reminder_lunch"] = "Almuerzo (HH:mm)",
        ["reminder_dinner"] = "Cena (HH:mm)",
        ["save_reminders"] = "Guardar recordatorios",
        ["reminders_saved"] = "Recordatorios actualizados",
        ["friends_title"] = "Amigos e invitaciones",
        ["invite_email_placeholder"] = "email@ejemplo.com",
        ["invite_friend"] = "Invitar",
        ["accept"] = "Aceptar",
        ["remove"] = "Eliminar",
        ["invite_invalid_email"] = "Correo inválido",
        ["invite_already_exists"] = "Ya invitado o ya amigo",
        ["invite_sent"] = "Invitación enviada",
        ["friend_accepted"] = "Amigo añadido",
        ["friend_removed"] = "Entrada eliminada",
        ["status_pending"] = "Invitación pendiente",
        ["status_friend"] = "Amigo",
        ["backend_api_title"] = "API Backend (PostgreSQL)",
        ["backend_api_placeholder"] = "https://api.nutritiontracker.fr",
        ["save_backend_api"] = "Guardar API",
        ["backend_api_saved_ok"] = "API guardada e identidad sincronizada",
        ["backend_api_saved_local_only"] = "API guardada (modo local)",
        ["saved_title_common"] = "Guardado",
        ["goals_saved_message"] = "Objetivos actualizados.\n+5 monedas ganadas · Saldo: {0}",
        ["login_title"] = "Iniciar sesión",
        ["login_subtitle"] = "Sigue calorías, proteínas y carbohidratos desde texto o foto.",
        ["login_google"] = "Continuar con Google",
        ["login_disclaimer"] = "Al continuar, aceptas enviar datos al servicio de análisis.",
        ["goals_title"] = "Objetivos",
        ["goal_cal_day"] = "Objetivo calorías / día",
        ["goal_protein_day"] = "Objetivo proteínas / día",
        ["goal_carbs_day"] = "Objetivo de carbohidratos / día",
        ["save"] = "Guardar",
        ["profile_title"] = "Perfil",
        ["language"] = "Idioma",
        ["current_lang_fr"] = "Idioma actual: Francés",
        ["current_lang_en"] = "Idioma actual: Inglés",
        ["current_lang_pt"] = "Idioma actual: Portugués (Brasil)",
        ["current_lang_es"] = "Idioma actual: Español (LatAm)",
        ["steps_today"] = "Pasos de hoy",
        ["advice_title"] = "Consejos",
        ["advice_hint"] = "Genera recomendaciones según tu historial.",
        ["generate_reco"] = "Generar recomendaciones",
        ["logout"] = "Cerrar sesión",
        ["main_loading"] = "Cargando...",
        ["recommendations_title"] = "Consejos",
        ["actions"] = "Acciones:",
        ["sync_ok"] = "Google Fit sincronizado",
        ["sync_no_token"] = "Inicia sesión de nuevo para autorizar Google Fit",
        ["sync_error"] = "Error de sincronización Google Fit",
        ["sync_disabled"] = "Integración de Google Fit temporalmente desactivada",
    };

    public static string T(string key)
    {
        var lang = Preferences.Default.Get("app_lang", "fr");
        var dict = lang switch
        {
            "en" => En,
            "pt" => Pt,
            "es" => Es,
            _ => Fr,
        };

        if (dict.TryGetValue(key, out var value)) return value;
        if (En.TryGetValue(key, out var en)) return en;
        if (Fr.TryGetValue(key, out var fr)) return fr;
        return key;
    }
}

[ContentProperty(nameof(Key))]
public class TranslateExtension : IMarkupExtension<string>
{
    public string Key { get; set; } = "";

    public string ProvideValue(IServiceProvider serviceProvider)
        => LocalizationService.T(Key);

    object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
        => ProvideValue(serviceProvider);
}
