using Microsoft.Maui.Controls.Xaml;

namespace NutritionTracker.Services;

public static class LocalizationService
{
    private static readonly Dictionary<string, string> Fr = new()
    {
        ["tab_dashboard"] = "Tableau",
        ["tab_diary"] = "Journal",
        ["tab_add"] = "Ajouter",
        ["tab_goals"] = "Objectifs",
        ["tab_stories"] = "Stories",
        ["tab_friends"] = "Amis",
        ["tab_profile"] = "Profil",

        ["dashboard_title"] = "Tableau",
        ["hello"] = "Bonjour,",
        ["record_meal_plus"] = "Enregistrer un repas +",
        ["advice"] = "Conseils",
        ["goals"] = "Objectifs",
        ["daily_summary"] = "Résumé du jour",
        ["daily_summary_hint"] = "Ajoutez vos repas (texte ou photo) pour suivre calories, protéines et glucides.",
        ["steps"] = "Pas",
        ["burned_calories"] = "Calories dépensées",
        ["net_calories"] = "Net calorique: {0}",
        ["reward_streak_title"] = "Série d'équilibre",
        ["reward_streak_subtitle"] = "Gagnez une flamme chaque jour équilibré (objectifs + charge).",
        ["balance_info_title"] = "Comment gagner des jours d'équilibre",
        ["balance_info_body"] = "Un jour équilibré valide au moins 2 critères sur 3 :\n• Calories nettes (apports - dépensées) dans ±15% de l'objectif\n• Protéines ≥ 90% de l'objectif\n• Glucides entre 80% et 120% de l'objectif\n\nAstuce : visez d'abord protéines + glucides, puis ajustez les calories nettes avec l'activité.",
        ["reward_balanced_today"] = "Objectifs équilibrés aujourd'hui : +1 flamme",
        ["reward_not_balanced_today"] = "Continuez : approchez calories nettes, protéines et glucides",
        ["reward_status_good"] = "Statut du jour : Équilibré ✅",
        ["reward_status_pending"] = "Statut du jour : À valider",
        ["social_notify_title"] = "Nouvelles interactions",
        ["recording_streak_title"] = "Série d'enregistrement",
        ["coins_balance"] = "Solde de pièces",
            ["reminder_title"] = "Rappels repas",
            ["reminder_enabled"] = "Activer",
            ["reminder_breakfast"] = "Petit-déjeuner (HH:mm)",
            ["reminder_lunch"] = "Déjeuner (HH:mm)",
            ["reminder_dinner"] = "Dîner (HH:mm)",
            ["save_reminders"] = "Enregistrer les rappels",
            ["reminders_saved"] = "Rappels mis à jour",
                ["reminders_failed"] = "Impossible d'activer les rappels (permission notifications requise)",
    ["backend_api_placeholder"] = "https://api.nutritiontracker.fr/api",
                ["friends_title"] = "Amis et invitations",
            ["invite_email_placeholder"] = "email@exemple.com",
            ["invite_friend"] = "Inviter",
                ["add_buddy"] = "Ajouter buddy",
                ["friends_league_title"] = "Ligue d'amis",
                ["friend_stories"] = "Stories",
                ["friend_message"] = "Message",
                ["friend_stories_title"] = "Stories de {0}",
                ["friend_no_stories"] = "Aucune story récente pour cet ami.",
                ["friend_action_signin_needed"] = "Reconnectez-vous pour utiliser cette action.",
                ["friend_message_to"] = "Envoyer un message à {0}",
                ["friend_message_unavailable"] = "Impossible d'envoyer un message pour le moment (aucune story récente de cet ami).",
                ["friend_message_failed"] = "Échec de l'envoi du message",
                ["story_meal"] = "Repas",
                ["story_message_placeholder"] = "Votre message",
                ["story_message_sent"] = "Message envoyé",
                ["send"] = "Envoyer",
                ["cancel"] = "Annuler",
            ["accept"] = "Accepter",
            ["remove"] = "Supprimer",
            ["invite_invalid_email"] = "Email invalide",
            ["invite_already_exists"] = "Déjà invité ou déjà ami",
            ["invite_sent"] = "Invitation envoyée",
                ["buddy_added"] = "Buddy ajouté",
                ["you"] = "vous",
            ["friend_accepted"] = "Ami ajouté",
            ["friend_removed"] = "Entrée supprimée",
            ["status_pending"] = "Invitation en attente",
            ["status_friend"] = "Ami",
            ["backend_api_title"] = "API Backend (PostgreSQL)",
            ["backend_api_placeholder"] = "https://api.nutritiontracker.fr/api",
            ["save_backend_api"] = "Enregistrer API",
            ["backend_api_saved_ok"] = "API enregistrée et identité synchronisée",
            ["backend_api_saved_local_only"] = "API enregistrée (mode local seulement)",
            ["saved_title_common"] = "Enregistré",
            ["goals_saved_message"] = "Objectifs mis à jour.\n+5 pièces gagnées · Solde : {0}",

        ["login_title"] = "Connexion",
        ["login_subtitle"] = "Suivez calories, protéines et glucides à partir d'un texte ou d'une photo.",
        ["login_google"] = "Continuer avec Google",
        ["login_disclaimer"] = "En continuant, vous acceptez d'envoyer vos données de repas au service d'analyse.",

        ["goals_title"] = "Objectifs",
        ["goal_cal_day"] = "Objectif calories / jour",
        ["goal_protein_day"] = "Objectif protéines / jour",
        ["goal_carbs_day"] = "Objectif glucides / jour",
        ["save"] = "Enregistrer",

        ["profile_title"] = "Profil",
        ["language"] = "Langue",
        ["current_lang_fr"] = "Langue actuelle : Français",
        ["current_lang_en"] = "Langue actuelle : Anglais",
        ["steps_today"] = "Pas aujourd'hui",
        ["advice_title"] = "Conseils",
        ["advice_hint"] = "Générez des recommandations basées sur votre historique.",
        ["generate_reco"] = "Générer des recommandations",
        ["logout"] = "Se déconnecter",

        ["main_loading"] = "Chargement...",

        ["recommendations_title"] = "Conseils",
        ["actions"] = "Actions :",

        ["sync_ok"] = "Google Fit synchronisé",
        ["sync_no_token"] = "Reconnectez-vous pour autoriser Google Fit",
        ["sync_error"] = "Sync Google Fit en échec",
        ["sync_disabled"] = "Intégration Google Fit temporairement désactivée",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["tab_dashboard"] = "Dashboard",
        ["tab_diary"] = "Diary",
        ["tab_add"] = "Add",
        ["tab_goals"] = "Goals",
        ["tab_stories"] = "Stories",
        ["tab_friends"] = "Friends",
        ["tab_profile"] = "Profile",

        ["dashboard_title"] = "Dashboard",
        ["hello"] = "Hello,",
        ["record_meal_plus"] = "Log meal +",
        ["advice"] = "Advice",
        ["goals"] = "Goals",
        ["daily_summary"] = "Daily summary",
        ["daily_summary_hint"] = "Add meals (text or photo) to track calories, protein and carbs.",
        ["steps"] = "Steps",
        ["burned_calories"] = "Burned calories",
        ["net_calories"] = "Net calories: {0}",
        ["reward_streak_title"] = "Balance streak",
        ["reward_streak_subtitle"] = "Earn one flame for each balanced day (goals + load).",
        ["balance_info_title"] = "How to earn balance days",
        ["balance_info_body"] = "A balanced day validates at least 2 of 3 criteria:\n• Net calories (intake - burned) within ±15% of target\n• Protein ≥ 90% of target\n• Carbs between 80% and 120% of target\n\nTip: hit protein + carbs first, then adjust net calories with activity.",
        ["reward_balanced_today"] = "Balanced today: +1 flame",
        ["reward_not_balanced_today"] = "Keep going: align net calories, protein and carbs",
        ["reward_status_good"] = "Today status: Balanced ✅",
        ["reward_status_pending"] = "Today status: Pending",
        ["social_notify_title"] = "New interactions",
            ["recording_streak_title"] = "Logging streak",
            ["coins_balance"] = "Coins balance",
            ["reminder_title"] = "Meal reminders",
            ["reminder_enabled"] = "Enable",
            ["reminder_breakfast"] = "Breakfast (HH:mm)",
            ["reminder_lunch"] = "Lunch (HH:mm)",
            ["reminder_dinner"] = "Dinner (HH:mm)",
            ["save_reminders"] = "Save reminders",
            ["reminders_saved"] = "Reminders updated",
                ["reminders_failed"] = "Unable to enable reminders (notification permission required)",
    ["backend_api_placeholder"] = "https://api.nutritiontracker.fr/api",
                ["friends_title"] = "Friends and invites",
            ["invite_email_placeholder"] = "email@example.com",
            ["invite_friend"] = "Invite",
                ["add_buddy"] = "Add buddy",
                ["friends_league_title"] = "Friends league",
                ["friend_stories"] = "Stories",
                ["friend_message"] = "Message",
                ["friend_stories_title"] = "{0}'s stories",
                ["friend_no_stories"] = "No recent stories for this friend.",
                ["friend_action_signin_needed"] = "Sign in again to use this action.",
                ["friend_message_to"] = "Send a message to {0}",
                ["friend_message_unavailable"] = "Unable to send a message right now (no recent story from this friend).",
                ["friend_message_failed"] = "Message failed to send",
                ["story_meal"] = "Meal",
                ["story_message_placeholder"] = "Your message",
                ["story_message_sent"] = "Message sent",
                ["send"] = "Send",
                ["cancel"] = "Cancel",
            ["accept"] = "Accept",
            ["remove"] = "Remove",
            ["invite_invalid_email"] = "Invalid email",
            ["invite_already_exists"] = "Already invited or already friend",
            ["invite_sent"] = "Invite sent",
                ["buddy_added"] = "Buddy added",
                ["you"] = "you",
            ["friend_accepted"] = "Friend added",
            ["friend_removed"] = "Entry removed",
            ["status_pending"] = "Pending invite",
            ["status_friend"] = "Friend",
            ["backend_api_title"] = "Backend API (PostgreSQL)",
            ["backend_api_placeholder"] = "https://api.nutritiontracker.fr/api",
            ["save_backend_api"] = "Save API",
            ["backend_api_saved_ok"] = "API saved and identity synced",
            ["backend_api_saved_local_only"] = "API saved (local-only mode)",
            ["saved_title_common"] = "Saved",
            ["goals_saved_message"] = "Goals updated.\n+5 coins earned · Balance: {0}",

        ["login_title"] = "Login",
        ["login_subtitle"] = "Track calories, protein and carbs from text or photo.",
        ["login_google"] = "Continue with Google",
        ["login_disclaimer"] = "By continuing, you agree to send meal data to the analysis service.",

        ["goals_title"] = "Goals",
        ["goal_cal_day"] = "Calories target / day",
        ["goal_protein_day"] = "Protein target / day",
        ["goal_carbs_day"] = "Carbs target / day",
        ["save"] = "Save",

        ["profile_title"] = "Profile",
        ["language"] = "Language",
        ["current_lang_fr"] = "Current language: French",
        ["current_lang_en"] = "Current language: English",
        ["current_lang_pt"] = "Current language: Portuguese (Brazil)",
        ["current_lang_es"] = "Current language: Spanish (LatAm)",
        ["steps_today"] = "Today's steps",
        ["advice_title"] = "Advice",
        ["advice_hint"] = "Generate recommendations from your history.",
        ["generate_reco"] = "Generate recommendations",
        ["logout"] = "Sign out",

        ["main_loading"] = "Loading...",

        ["recommendations_title"] = "Advice",
        ["actions"] = "Actions:",

        ["sync_ok"] = "Google Fit synced",
        ["sync_no_token"] = "Sign in again to allow Google Fit",
        ["sync_error"] = "Google Fit sync failed",
        ["sync_disabled"] = "Google Fit integration temporarily disabled",
    };

    private static readonly Dictionary<string, string> Pt = new()
    {
        ["tab_dashboard"] = "Painel",
        ["tab_diary"] = "Diário",
        ["tab_add"] = "Adicionar",
        ["tab_goals"] = "Metas",
        ["tab_stories"] = "Stories",
        ["tab_friends"] = "Amigos",
        ["tab_profile"] = "Perfil",
        ["dashboard_title"] = "Painel",
        ["hello"] = "Olá,",
        ["record_meal_plus"] = "Registrar refeição +",
        ["advice"] = "Conselhos",
        ["goals"] = "Metas",
        ["daily_summary"] = "Resumo diário",
        ["daily_summary_hint"] = "Adicione refeições (texto ou foto) para acompanhar calorias, proteínas e carboidratos.",
        ["steps"] = "Passos",
        ["burned_calories"] = "Calorias queimadas",
        ["net_calories"] = "Calorias líquidas: {0}",
        ["reward_streak_title"] = "Sequência de equilíbrio",
        ["reward_streak_subtitle"] = "Ganhe uma chama para cada dia equilibrado (metas + carga).",
        ["balance_info_title"] = "Como ganhar dias de equilíbrio",
        ["balance_info_body"] = "Um dia equilibrado valida pelo menos 2 de 3 critérios:\n• Calorias líquidas (ingeridas - queimadas) em ±15% da meta\n• Proteínas ≥ 90% da meta\n• Carboidratos entre 80% e 120% da meta\n\nDica: priorize proteínas + carboidratos e ajuste as calorias líquidas com atividade.",
        ["reward_balanced_today"] = "Equilibrado hoje: +1 chama",
        ["reward_not_balanced_today"] = "Continue: alinhe calorias líquidas, proteínas e carboidratos",
        ["reward_status_good"] = "Status de hoje: Equilibrado ✅",
        ["reward_status_pending"] = "Status de hoje: Pendente",
        ["social_notify_title"] = "Novas interações",
        ["recording_streak_title"] = "Sequência de registros",
        ["coins_balance"] = "Saldo de moedas",
        ["reminder_title"] = "Lembretes de refeição",
        ["reminder_enabled"] = "Ativar",
        ["reminder_breakfast"] = "Café da manhã (HH:mm)",
        ["reminder_lunch"] = "Almoço (HH:mm)",
        ["reminder_dinner"] = "Jantar (HH:mm)",
        ["save_reminders"] = "Salvar lembretes",
        ["reminders_saved"] = "Lembretes atualizados",
        ["reminders_failed"] = "Não foi possível ativar lembretes (permissão de notificações necessária)",
        ["friends_title"] = "Amigos e convites",
        ["invite_email_placeholder"] = "email@exemplo.com",
        ["invite_friend"] = "Convidar",
        ["add_buddy"] = "Adicionar buddy",
        ["friends_league_title"] = "Liga de amigos",
        ["friend_stories"] = "Stories",
        ["friend_message"] = "Mensagem",
        ["friend_stories_title"] = "Stories de {0}",
        ["friend_no_stories"] = "Nenhuma story recente para este amigo.",
        ["friend_action_signin_needed"] = "Faça login novamente para usar esta ação.",
        ["friend_message_to"] = "Enviar mensagem para {0}",
        ["friend_message_unavailable"] = "Não foi possível enviar mensagem agora (sem story recente deste amigo).",
        ["friend_message_failed"] = "Falha ao enviar mensagem",
        ["story_meal"] = "Refeição",
        ["story_message_placeholder"] = "Sua mensagem",
        ["story_message_sent"] = "Mensagem enviada",
        ["send"] = "Enviar",
        ["cancel"] = "Cancelar",
        ["accept"] = "Aceitar",
        ["remove"] = "Remover",
        ["invite_invalid_email"] = "Email inválido",
        ["invite_already_exists"] = "Já convidado ou já amigo",
        ["invite_sent"] = "Convite enviado",
        ["buddy_added"] = "Buddy adicionado",
        ["you"] = "você",
        ["friend_accepted"] = "Amigo adicionado",
        ["friend_removed"] = "Entrada removida",
        ["status_pending"] = "Convite pendente",
        ["status_friend"] = "Amigo",
        ["backend_api_title"] = "API Backend (PostgreSQL)",
        ["backend_api_placeholder"] = "https://api.nutritiontracker.fr/api",
        ["save_backend_api"] = "Salvar API",
        ["backend_api_saved_ok"] = "API salva e identidade sincronizada",
        ["backend_api_saved_local_only"] = "API salva (modo local)",
        ["saved_title_common"] = "Salvo",
        ["goals_saved_message"] = "Metas atualizadas.\n+5 moedas ganhas · Saldo: {0}",
        ["login_title"] = "Entrar",
        ["login_subtitle"] = "Acompanhe calorias, proteínas e carboidratos por texto ou foto.",
        ["login_google"] = "Continuar com Google",
        ["login_disclaimer"] = "Ao continuar, você concorda em enviar dados ao serviço de análise.",
        ["goals_title"] = "Metas",
        ["goal_cal_day"] = "Meta de calorias / dia",
        ["goal_protein_day"] = "Meta de proteínas / dia",
        ["goal_carbs_day"] = "Meta de carboidratos / dia",
        ["save"] = "Salvar",
        ["profile_title"] = "Perfil",
        ["language"] = "Idioma",
        ["current_lang_fr"] = "Idioma atual: Francês",
        ["current_lang_en"] = "Idioma atual: Inglês",
        ["current_lang_pt"] = "Idioma atual: Português (Brasil)",
        ["current_lang_es"] = "Idioma atual: Espanhol (LatAm)",
        ["steps_today"] = "Passos de hoje",
        ["advice_title"] = "Conselhos",
        ["advice_hint"] = "Gere recomendações com base no seu histórico.",
        ["generate_reco"] = "Gerar recomendações",
        ["logout"] = "Sair",
        ["main_loading"] = "Carregando...",
        ["recommendations_title"] = "Conselhos",
        ["actions"] = "Ações:",
        ["sync_ok"] = "Google Fit sincronizado",
        ["sync_no_token"] = "Entre novamente para autorizar Google Fit",
        ["sync_error"] = "Falha na sincronização do Google Fit",
        ["sync_disabled"] = "Integração com Google Fit temporariamente desativada",
    };

    private static readonly Dictionary<string, string> Es = new()
    {
        ["tab_dashboard"] = "Panel",
        ["tab_diary"] = "Diario",
        ["tab_add"] = "Añadir",
        ["tab_goals"] = "Objetivos",
        ["tab_stories"] = "Stories",
        ["tab_friends"] = "Amigos",
        ["tab_profile"] = "Perfil",
        ["dashboard_title"] = "Panel",
        ["hello"] = "Hola,",
        ["record_meal_plus"] = "Registrar comida +",
        ["advice"] = "Consejos",
        ["goals"] = "Objetivos",
        ["daily_summary"] = "Resumen diario",
        ["daily_summary_hint"] = "Añade comidas (texto o foto) para seguir calorías, proteínas y carbohidratos.",
        ["steps"] = "Pasos",
        ["burned_calories"] = "Calorías quemadas",
        ["net_calories"] = "Calorías netas: {0}",
        ["reward_streak_title"] = "Racha de equilibrio",
        ["reward_streak_subtitle"] = "Gana una llama por cada día equilibrado (objetivos + carga).",
        ["balance_info_title"] = "Cómo ganar días de equilibrio",
        ["balance_info_body"] = "Un día equilibrado valida al menos 2 de 3 criterios:\n• Calorías netas (ingeridas - quemadas) dentro de ±15% del objetivo\n• Proteínas ≥ 90% del objetivo\n• Carbohidratos entre 80% y 120% del objetivo\n\nConsejo: prioriza proteínas + carbohidratos y luego ajusta las calorías netas con actividad.",
        ["reward_balanced_today"] = "Equilibrado hoy: +1 llama",
        ["reward_not_balanced_today"] = "Sigue: ajusta calorías netas, proteínas y carbohidratos",
        ["reward_status_good"] = "Estado de hoy: Equilibrado ✅",
        ["reward_status_pending"] = "Estado de hoy: Pendiente",
        ["social_notify_title"] = "Nuevas interacciones",
        ["recording_streak_title"] = "Racha de registro",
        ["coins_balance"] = "Saldo de monedas",
        ["reminder_title"] = "Recordatorios de comida",
        ["reminder_enabled"] = "Activar",
        ["reminder_breakfast"] = "Desayuno (HH:mm)",
        ["reminder_lunch"] = "Almuerzo (HH:mm)",
        ["reminder_dinner"] = "Cena (HH:mm)",
        ["save_reminders"] = "Guardar recordatorios",
        ["reminders_saved"] = "Recordatorios actualizados",
        ["reminders_failed"] = "No se pudieron activar los recordatorios (permiso de notificaciones requerido)",
        ["friends_title"] = "Amigos e invitaciones",
        ["invite_email_placeholder"] = "email@ejemplo.com",
        ["invite_friend"] = "Invitar",
        ["add_buddy"] = "Agregar buddy",
        ["friends_league_title"] = "Liga de amigos",
        ["friend_stories"] = "Stories",
        ["friend_message"] = "Mensaje",
        ["friend_stories_title"] = "Stories de {0}",
        ["friend_no_stories"] = "No hay stories recientes para este amigo.",
        ["friend_action_signin_needed"] = "Vuelve a iniciar sesión para usar esta acción.",
        ["friend_message_to"] = "Enviar mensaje a {0}",
        ["friend_message_unavailable"] = "No se puede enviar mensaje ahora (sin story reciente de este amigo).",
        ["friend_message_failed"] = "Error al enviar el mensaje",
        ["story_meal"] = "Comida",
        ["story_message_placeholder"] = "Tu mensaje",
        ["story_message_sent"] = "Mensaje enviado",
        ["send"] = "Enviar",
        ["cancel"] = "Cancelar",
        ["accept"] = "Aceptar",
        ["remove"] = "Eliminar",
        ["invite_invalid_email"] = "Correo inválido",
        ["invite_already_exists"] = "Ya invitado o ya amigo",
        ["invite_sent"] = "Invitación enviada",
        ["buddy_added"] = "Buddy agregado",
        ["you"] = "tú",
        ["friend_accepted"] = "Amigo añadido",
        ["friend_removed"] = "Entrada eliminada",
        ["status_pending"] = "Invitación pendiente",
        ["status_friend"] = "Amigo",
        ["backend_api_title"] = "API Backend (PostgreSQL)",
        ["backend_api_placeholder"] = "https://api.nutritiontracker.fr/api",
        ["save_backend_api"] = "Guardar API",
        ["backend_api_saved_ok"] = "API guardada e identidad sincronizada",
        ["backend_api_saved_local_only"] = "API guardada (modo local)",
        ["saved_title_common"] = "Guardado",
        ["goals_saved_message"] = "Objetivos actualizados.\n+5 monedas ganadas · Saldo: {0}",
        ["login_title"] = "Iniciar sesión",
        ["login_subtitle"] = "Sigue calorías, proteínas y carbohidratos desde texto o foto.",
        ["login_google"] = "Continuar con Google",
        ["login_disclaimer"] = "Al continuar, aceptas enviar datos al servicio de análisis.",
        ["goals_title"] = "Objetivos",
        ["goal_cal_day"] = "Objetivo calorías / día",
        ["goal_protein_day"] = "Objetivo proteínas / día",
        ["goal_carbs_day"] = "Objetivo de carbohidratos / día",
        ["save"] = "Guardar",
        ["profile_title"] = "Perfil",
        ["language"] = "Idioma",
        ["current_lang_fr"] = "Idioma actual: Francés",
        ["current_lang_en"] = "Idioma actual: Inglés",
        ["current_lang_pt"] = "Idioma actual: Portugués (Brasil)",
        ["current_lang_es"] = "Idioma actual: Español (LatAm)",
        ["steps_today"] = "Pasos de hoy",
        ["advice_title"] = "Consejos",
        ["advice_hint"] = "Genera recomendaciones según tu historial.",
        ["generate_reco"] = "Generar recomendaciones",
        ["logout"] = "Cerrar sesión",
        ["main_loading"] = "Cargando...",
        ["recommendations_title"] = "Consejos",
        ["actions"] = "Acciones:",
        ["sync_ok"] = "Google Fit sincronizado",
        ["sync_no_token"] = "Inicia sesión de nuevo para autorizar Google Fit",
        ["sync_error"] = "Error de sincronización Google Fit",
        ["sync_disabled"] = "Integración de Google Fit temporalmente desactivada",
    };

    public static string T(string key)
    {
        var lang = Preferences.Default.Get("app_lang", "fr");
        var dict = lang switch
        {
            "en" => En,
            "pt" => Pt,
            "es" => Es,
            _ => Fr,
        };

        if (dict.TryGetValue(key, out var value)) return value;
        if (En.TryGetValue(key, out var en)) return en;
        if (Fr.TryGetValue(key, out var fr)) return fr;
        return key;
    }
}

[ContentProperty(nameof(Key))]
public class TranslateExtension : IMarkupExtension<string>
{
    public string Key { get; set; } = "";

    public string ProvideValue(IServiceProvider serviceProvider)
        => LocalizationService.T(Key);

    object IMarkupExtension.ProvideValue(IServiceProvider serviceProvider)
        => ProvideValue(serviceProvider);
}
